global using AutoMapper;
global using AutoMapper.QueryableExtensions;
global using Microsoft.EntityFrameworkCore;
global using FluentValidation;
global using MediatR;
global using TP.Domain.Common;
global using TP.Application.Common.Interfaces;
global using TP.Domain.Exceptions;
global using TP.Application.Common.Pagination;
